version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: "nginx-consul"
    ports:
      - 7071:443
      - 9091:80
    depends_on:
      - "consul"
    volumes: 
      - ./nginx/log:/var/log/nginx
      - ./nginx/ssl:/etc/ssl/certs
      - ./nginx/private:/etc/ssl/private
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/conf:/etc/nginx
      - ./nginx/consul_template:/templates
    environment:
      - CONSUL=consul 
    links:
      - consul:consul
    restart: always

  apache:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    image: "php-apache-server"
    volumes: 
      - ./apache/web:/var/www/html
      - ./apache/conf:/var/conf
    links:
      - mysql:dbserver
    environment:
      - DATABASE
      - MYSQL_PASSWORD
      - MYSQL_USER
      - SERVICE_NAME=orangehrm-apache
    #restart: always

 
  mysql:
    image: "mysql-server"
    build:
      context: .
      dockerfile: ./mysql/dockerfile
    volumes: 
      - ./mysql/sql:/docker-entrypoint-initdb.d/
      - ./mysql/conf:/var/conf
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_USER
    #restart: always      
      

  #consul:
   # image: "consul-server"
    #build:
     # context: .
      #dockerfile: ./consul/dockerfile
    #restart: always 

 
  consul: 
    image: gliderlabs/consul-server  
    #restart: always 
    volumes:     
      - /var/run/docker.sock:/tmp/docker.sock    
      - /etc/localtime:/etc/localtime  
    command: -server -bootstrap
  
  serviceregistry:
    image: "registry"
    #depends_on:
     # - "consul"
    build:
      context: .
      dockerfile: ./registrator/dockerfile 
    links:
      - consul:consulserver
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock
    entrypoint: /bin/registrator consul://consul:8500
    environment:
      - CONSUL=consul
      - consul=//consul:8500 
      
      
      
      
      
      
      
      
      
      
      
      
